planet_parameters : {
  # From ExoFOP website (TOIs TESS Project)
  epoch : 2459500.53574,
  period : 3.3366510632883,
  # From Kokori et al. 2023 (Exoplanetary archive)
  rp : 0.0764,
  a : 13.9,
  inc : 88.9,
  ecc : 0.017,
  w : 1.7,
}

stellar_parameters : {
  # From Kosiarek et al. 2019 (Exoplanetary archive)
  teff : [3652, 50],
  logg : [4.658, 0.035],
  z : [0.2, 0.1],
}
